### ISSUE TITLE
squishes up my header DIV

### ISSUE THREAD

**Issue by FurmanSK** [dpoetzsch/md-pickers#10]
When using this inside a md-tab container, my header div that is above it gets squished up when I open a mdp-time-picker. Any reason for this? I'll see if I can get some example but its on my intranet sites at work.

**Comment by FurmanSK** [comment]
To add to this, I added min-height CSS to my header class and it fixed some of it but now it adds a overflow scroll bar to my tabs area when the mdp-time-picker dialog is active. Then when it goes away the main overflow scroll for the page comes back causing the title to shift. Not sure if it's an issue or just something unique to my page.

**Comment by anurbol** [comment]
i am not maintainer but you should create codepen example

**Comment by FurmanSK** [comment]
Well I think I fixed it. I set a min-height for my DIV and removed the <md-content> around my whole form body and works fine now. So I believe it was just a unique situation. Closing
