### ISSUE TITLE
Ability to configure global options

### ISSUE THREAD

**Issue by robin-thoni** [dpoetzsch/md-pickers#11]
It would be great to be able to configure all date and time pickers at once, with a service like [$mdDateLocaleProvider](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider). You could even use it for the date picker and create another for the time picker.

The service(s) should expose all needed options (time/date format, AM/PM, first day of the week, etc).

**Comment by dpoetzsch** [comment]
I agree. Although I'm not sure if configuring this on a provider level is the right thing to do as it makes it very hard to switch localizations at run time.

I'd vote for the service that can be changed at any time. Would you be interested in creating a pull request?

**Comment by robin-thoni** [comment]
For `$mdDateLocaleProvider`, I just inject `$mdDateLocale` in `run()`, but it's not officially supported (https://github.com/angular/material/issues/4480). So yes, a regular service might be better. The only down side is that we should configure both `$mdDateLocaleProvider` and the newly created services (in case you're using some components that need it).

Well, why not, I'll try to take some time this week.

**Comment by dpoetzsch** [comment]
closed by pull request #12
