### ISSUE TITLE
Cancel button behavior

### ISSUE THREAD

**Issue by robin-thoni** [dpoetzsch/md-pickers#14]
The cancel button cancel the dialog (which is normal) but also clears the date, which is a little bit confusing, in my opinion. It might be a good thing to be able to cancel the dialog without setting the date to null.

Maybe just adding a clear button and stop reseting on cancel?

**Comment by dpoetzsch** [comment]
Oh yeah, I think this was broken by pull request #8. I will look into your PR as a better alternative

**Comment by dpoetzsch** [comment]
closed by pull request #18
