### ISSUE TITLE
Roadmap: Typescript

### ISSUE THREAD

**Issue by omar10594** [dpoetzsch/md-pickers#32]
this mean rewrite all with typescript, or only support typescript (create type definitions).

I want to help with this, so i want to know if you have some progress on this.

**Comment by dpoetzsch** [comment]
I'm a huge fan of typescript so I'd love to have the time to rewrite the lib in typescript. However, so far I could not find the time to start this.

It might make sense to do this only for a new version that supports angular 2/4/5 (see #19). I feel that much effort into angular 1 might end up being a waste of time in the future.
