### ISSUE TITLE
build: the latest npm package 1.1.4 contains .git folder

### ISSUE THREAD

**Issue by k4Shinigami** [dpoetzsch/md-pickers#43]
Steps:

1. npm i md-pickers@1.1.4
2. check node_modules/md-picker/ directory

It has .git folder which breaks the builds. 

more details:

> npm ERR! code EISGIT
> npm ERR! git /Users/sasideep/github/proj/node_modules/md-pickers: Appears to be a git repo or submodule.
> npm ERR! git     /Users/sasideep/github/proj/node_modules/md-pickers
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.
> 

Could you please remove the `.git` folder and publish again to npm?

Thanks.

**Comment by dpoetzsch** [comment]
Thanks for the notice!
